[[plugins]]
repo='Shougo/dein.vim'

[[plugins]]
repo='Shougo/neosnippet.vim'

[[plugins]]
repo='Shougo/neosnippet-snippets'

[[plugins]]
repo='Shougo/vimshell'
rev='3787e5'

[[plugins]]
repo='tpope/vim-fugitive'
[[plugins]]
repo='ctrlpvim/ctrlp.vim'
[[plugins]]
repo='flazz/vim-colorschemes'

[[plugins]]
repo='w0ng/vim-hybrid'

# 補完プラグイン
[[plugins]]
repo='Shougo/neocomplcache'

# コメントアウト
[[plugins]]
repo='scrooloose/nerdcommenter'

# 対応する括弧を自動入力
[[plugins]]
repo='Townk/vim-autoclose'

# f + 一文字で検索
[[plugins]]
repo='rhysd/clever-f.vim'

# s + 二文字で検索
[[plugins]]
repo='goldfeld/vim-seek'

# ステータスバーのプラグイン
[[plugins]]
repo='itchyny/lightline.vim'

# ステータスバー用のhybridのcolorscheme
[[plugins]]
repo='cocopon/lightline-hybrid.vim'

# テキストを整列させるプラグイン
[[plugins]]
repo='godlygeek/tabular'
# repo='junegunn/vim-easy-align'

# ブラウザを開くコマンドを追加
[[plugins]]
repo='tyru/open-browser.vim'

# indentの深さに色をつける
[[plugins]]
repo='nathanaelkane/vim-indent-guides'

# quickrun
[[plugins]]
repo='thinca/vim-quickrun'

# カーソル移動加速プラグイン
[[plugins]]
repo='rhysd/accelerated-jk'

# Unite
[[plugins]]
repo='Shougo/unite.vim'
[[plugins]]
repo='Shougo/neomru.vim'
[[plugins]]
repo='Shougo/vimfiler.vim'

# reference viewer
[[plugins]]
repo='thinca/vim-ref'

# 行末の不要な半角スペースを可視化
[[plugins]]
repo='ntpeters/vim-better-whitespace'

# text-objectを囲むプラグイン(ys + text-object)
[[plugins]]
repo='tpope/vim-surround'
[[plugins]]
repo='tpope/vim-repeat'

# vimからctagsを使う
[[plugins]]
repo='szw/vim-tags'

# タブ作成・移動・削除
[[plugins]]
repo='watanany/vim-tabs'

# カーソル移動
# repo='Lokaltog/vim-easymotion'

# セッション保存
[[plugins]]
repo='tpope/vim-obsession'


#--------------------------------------------------------------------------------
# HTML
#--------------------------------------------------------------------------------
# HTML5 Syntax
[[plugins]]
repo='othree/html5.vim'
on_ft=['html', 'erb']

# HTMLのショートカットプラグイン
[[plugins]]
repo='mattn/emmet-vim'
on_ft=['html', 'erb']

# Markdown, reStructuredText, textile プレビュープラグイン
[[plugins]]
repo='kannokanno/previm'
on_ft=['markdown']

#--------------------------------------------------------------------------------
# CSS
#--------------------------------------------------------------------------------
[[plugins]]
repo='hail2u/vim-css3-syntax'
on_ft=['css', 'less', 'scss', 'sass']

#--------------------------------------------------------------------------------
# JavaScript
#--------------------------------------------------------------------------------
[[plugins]]
repo='vim-scripts/jQuery'
on_ft=['javascript']

[[plugins]]
repo='jelera/vim-javascript-syntax'
on_ft=['javascript']

[[plugins]]
repo='mattn/jscomplete-vim'
on_ft=['javascript']

#--------------------------------------------------------------------------------
# CoffeeScript
#--------------------------------------------------------------------------------
# coffee scriptのsyntax + 自動compileのプラグイン
[[plugins]]
repo='kchmck/vim-coffee-script'
on_ft=['coffee']

[[plugins]]
repo='digitaltoad/vim-pug'
on_ft=['coffee']

#--------------------------------------------------------------------------------
# Ruby
#--------------------------------------------------------------------------------
[[plugins]]
repo='vim-scripts/ruby-matchit'
on_ft=['ruby', 'erb', 'haml']

[[plugins]]
repo='tpope/vim-endwise'
on_ft=['ruby', 'erb', 'haml']

[[plugins]]
repo='yuku-t/vim-ref-ri'
on_ft=['ruby', 'erb', 'haml']

# Ruby on Rails
[[plugins]]
repo='tpope/vim-rails'
on_ft=['ruby', 'erb', 'haml']

[[plugins]]
repo='tpope/vim-bundler'
on_ft=['ruby', 'erb', 'haml']

[[plugins]]
repo='basyura/unite-rails'
on_ft=['ruby', 'erb', 'haml']

[[plugins]]
repo='scrooloose/syntastic'
on_ft=['ruby', 'erb', 'haml']


#--------------------------------------------------------------------------------
# Python
#--------------------------------------------------------------------------------
[[plugins]]
repo='davidhalter/jedi-vim'
on_ft=['python']
[[plugins]]
repo='lambdalisue/vim-pyenv'
on_ft=['python']

#--------------------------------------------------------------------------------
# Haskell
#--------------------------------------------------------------------------------
[[plugins]]
repo='kana/vim-filetype-haskell'
on_ft=['haskell']

[[plugins]]
repo='eagletmt/ghcmod-vim'
on_ft=['haskell']

[[plugins]]
repo='ujihisa/neco-ghc'
on_ft=['haskell']

# [[plugins]]
# repo='osyo-manga/vim-watchdogs'
# on_ft=['haskell']

[[plugins]]
repo='ujihisa/ref-hoogle'
on_ft=['haskell']

[[plugins]]
repo='ujihisa/unite-haskellimport'
on_ft=['haskell']

#--------------------------------------------------------------------------------
# Scala
#--------------------------------------------------------------------------------
[[plugins]]
repo='derekwyatt/vim-scala'
on_ft=['scala']

#--------------------------------------------------------------------------------
# Elixir
#--------------------------------------------------------------------------------
[[plugins]]
repo='elixir-lang/vim-elixir'
on_ft=['elixir']
